# Generated by Django 4.2.7 on 2023-11-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_users_groups_alter_users_user_permissions"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="users",
            managers=[],
        ),
    ]
