# Generated by Django 4.2.7 on 2023-11-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_users_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
