# Generated by Django 4.2.7 on 2023-11-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_users_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
