# Generated by Django 4.2.7 on 2023-11-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_users_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={},
        ),
        migrations.AlterModelManagers(
            name="users",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="users",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="users",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="users",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="users",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="users",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="users",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="users",
            name="username",
        ),
    ]
