# Generated by Django 4.2.7 on 2023-11-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_users_options_alter_users_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=30),
        ),
    ]
