# Generated by Django 4.2.7 on 2023-11-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_users_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="is_superuser",
        ),
    ]
